### ISSUE TITLE
Unable to find Calculator "MyPassThroughCalculator"

### ISSUE THREAD

**Issue by faaip** [madelinegannon/example-mediapipe-udp#1] opened 2020-04-27 14:22 UTC
Hi @madelinegannon .

Thank you so much for this and for the very detailed instructions. I tried running 

```
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu     --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt
```

and get the following errors:

```
WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/805e47cea96c7e8c6fccf494d40a2392dc99fdd8.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "c839ff09c038f291a6935c8fc2a5874b4c4612059ba8f54314cbf39186e108d4"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_frederikjuutilainen/aacdf75d08bc263b7b69433e3bb50764/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/v3.11.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/05702cf4099ad019ad1abb8ba656bfe04304f32a.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/Maratyszcza/pthreadpool/archive/76042155a8b1e189c8f141429fd72219472c32e1.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu up-to-date:
  bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu
INFO: Elapsed time: 1.161s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
I0427 16:12:21.331287 274976192 demo_run_graph_main.cc:47] Get calculator graph config contents: # Add New Node
node {
  calculator: "MyPassThroughCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "NORM_RECT:hand_rect"
  input_stream: "DETECTIONS:palm_detections"
  output_stream: "LANDMARKS:hand_landmarks_out"
  output_stream: "NORM_RECT:hand_rect_out"
  output_stream: "DETECTIONS:palm_detections_out"
}

# Modify input_stream names of next node

# Subgraph that renders annotations and overlays them on top of the input
# images (see renderer_cpu.pbtxt).
node {
  calculator: "RendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "LANDMARKS:hand_landmarks_out"
  input_stream: "NORM_RECT:hand_rect_out"
  input_stream: "DETECTIONS:palm_detections_out"
  output_stream: "IMAGE:output_video"
}
I0427 16:12:21.333701 274976192 demo_run_graph_main.cc:53] Initialize the calculator graph.
E0427 16:12:21.334813 274976192 demo_run_graph_main.cc:146] Failed to run the graph: ValidatedGraphConfig Initialization failed.
No registered object with name: MyPassThroughCalculator; Unable to find Calculator "MyPassThroughCalculator" 
```

From the error it seems that MyPassThroughCalculator cannot be found, but I have double-checked that I did indeed copy the file src/mediapipe/my_pass_though_calculator.cc to my Mediapipe calculators directory.

```
ls mediapipe/calculators/core 
                                     
BUILD                                             matrix_to_vector_calculator_test.cc
add_header_calculator.cc                          merge_calculator.cc
add_header_calculator_test.cc                     merge_calculator_test.cc
begin_end_loop_calculator_graph_test.cc           mux_calculator.cc
begin_loop_calculator.cc                          my_pass_through_calculator.cc
begin_loop_calculator.h                           packet_cloner_calculator.cc
clip_detection_vector_size_calculator.cc          packet_cloner_calculator.proto
clip_vector_size_calculator.cc                    packet_inner_join_calculator.cc
clip_vector_size_calculator.h                     packet_inner_join_calculator_test.cc
clip_vector_size_calculator.proto                 packet_resampler_calculator.cc
clip_vector_size_calculator_test.cc               packet_resampler_calculator.h
concatenate_detection_vector_calculator.cc        packet_resampler_calculator.proto
concatenate_vector_calculator.cc                  packet_resampler_calculator_test.cc
concatenate_vector_calculator.h                   packet_thinner_calculator.cc
concatenate_vector_calculator.proto               packet_thinner_calculator.proto
concatenate_vector_calculator_test.cc             packet_thinner_calculator_test.cc
constant_side_packet_calculator.cc                pass_through_calculator.cc
constant_side_packet_calculator.proto             previous_loopback_calculator.cc
constant_side_packet_calculator_test.cc           previous_loopback_calculator_test.cc
counting_source_calculator.cc                     quantize_float_vector_calculator.cc
dequantize_byte_array_calculator.cc               quantize_float_vector_calculator.proto
dequantize_byte_array_calculator.proto            quantize_float_vector_calculator_test.cc
dequantize_byte_array_calculator_test.cc          round_robin_demux_calculator.cc
end_loop_calculator.cc                            sequence_shift_calculator.cc
end_loop_calculator.h                             sequence_shift_calculator.proto
flow_limiter_calculator.cc                        sequence_shift_calculator_test.cc
flow_limiter_calculator_test.cc                   side_packet_to_stream_calculator.cc
gate_calculator.cc                                side_packet_to_stream_calculator_test.cc
gate_calculator.proto                             split_normalized_landmark_list_calculator.cc
gate_calculator_test.cc                           split_normalized_landmark_list_calculator_test.cc
immediate_mux_calculator.cc                       split_vector_calculator.cc
immediate_mux_calculator_test.cc                  split_vector_calculator.h
make_pair_calculator.cc                           split_vector_calculator.proto
matrix_multiply_calculator.cc                     split_vector_calculator_test.cc
matrix_multiply_calculator_test.cc                stream_to_side_packet_calculator.cc
matrix_subtract_calculator.cc                     stream_to_side_packet_calculator_test.cc
matrix_subtract_calculator_test.cc                string_to_int_calculator.cc
matrix_to_vector_calculator.cc

```

I have also followed step 3 and appended to the BUILD file.

Sorry for this, it's probably just an stupid overlook on my part. :)

All the best,
Frederik

**Comment by madelinegannon** [comment] 2020-04-27 15:09
You also need to modify the _mediapipe/graphs/hand_tracking/BUILD_ file to add the new calculator as a dependency:

```
cc_library(
    name = "desktop_offline_calculators",
    deps = [
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/calculators/core:gate_calculator",
        "//mediapipe/calculators/core:immediate_mux_calculator",
        "//mediapipe/calculators/core:packet_inner_join_calculator",
        "//mediapipe/calculators/core:previous_loopback_calculator",
        "//mediapipe/calculators/video:opencv_video_decoder_calculator",
        "//mediapipe/calculators/video:opencv_video_encoder_calculator",
        "//mediapipe/calculators/core:my_pass_through_calculator"
    ],
)
```

Thanks for pointing this out! This step is missing in the README. I'll add it in now :)

Let me know how it works and if you hit any other issues.

**Comment by faaip** [comment] 2020-04-28 07:23
Hi Madeline.

Thanks for the help! I modified the handtracking BUILD file and now run into the following error:

```
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (2 packages loaded, 42 targets configured).
INFO: Found 1 target...
ERROR: /Users/frederikjuutilainen/Programming/mediapipe/mediapipe/calculators/core/BUILD:1066:1: C++ compilation of rule '//mediapipe/calculators/core:my_pass_through_calculator' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 68 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/core/my_pass_through_calculator.cc:22:10: fatal error: 'mediapipe/framework/formats/wrapper_hand_tracking.pb.h' file not found
#include "mediapipe/framework/formats/wrapper_hand_tracking.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.415s, Critical Path: 2.53s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
I0428 09:20:50.272465 288341440 demo_run_graph_main.cc:47] Get calculator graph config contents: # MediaPipe graph that performs hand tracking on desktop with TensorFlow Lite
# on CPU.
# Used in the example in
# mediapipie/examples/desktop/hand_tracking:hand_tracking_cpu.

# Images coming into and out of the graph.
input_stream: "input_video"
output_stream: "output_video"

# Caches a hand-presence decision fed back from HandLandmarkSubgraph, and upon
# the arrival of the next input image sends out the cached decision with the
# timestamp replaced by that of the input image, essentially generating a packet
# that carries the previous hand-presence decision. Note that upon the arrival
# of the very first input image, an empty packet is sent out to jump start the
# feedback loop.
node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:input_video"
  input_stream: "LOOP:hand_presence"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:prev_hand_presence"
}

# Drops the incoming image if HandLandmarkSubgraph was able to identify hand
# presence in the previous image. Otherwise, passes the incoming image through
# to trigger a new round of hand detection in HandDetectionSubgraph.
node {
  calculator: "GateCalculator"
  input_stream: "input_video"
  input_stream: "DISALLOW:prev_hand_presence"
  output_stream: "hand_detection_input_video"

  node_options: {
    [type.googleapis.com/mediapipe.GateCalculatorOptions] {
      empty_packets_as_allow: true
    }
  }
}

# Subgraph that detections hands (see hand_detection_cpu.pbtxt).
node {
  calculator: "HandDetectionSubgraph"
  input_stream: "hand_detection_input_video"
  output_stream: "DETECTIONS:palm_detections"
  output_stream: "NORM_RECT:hand_rect_from_palm_detections"
}

# Subgraph that localizes hand landmarks (see hand_landmark_cpu.pbtxt).
node {
  calculator: "HandLandmarkSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "NORM_RECT:hand_rect"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "NORM_RECT:hand_rect_from_landmarks"
  output_stream: "PRESENCE:hand_presence"
}

# Caches a hand rectangle fed back from HandLandmarkSubgraph, and upon the
# arrival of the next input image sends out the cached rectangle with the
# timestamp replaced by that of the input image, essentially generating a packet
# that carries the previous hand rectangle. Note that upon the arrival of the
# very first input image, an empty packet is sent out to jump start the
# feedback loop.
node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:input_video"
  input_stream: "LOOP:hand_rect_from_landmarks"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:prev_hand_rect_from_landmarks"
}

# Merges a stream of hand rectangles generated by HandDetectionSubgraph and that
# generated by HandLandmarkSubgraph into a single output stream by selecting
# between one of the two streams. The former is selected if the incoming packet
# is not empty, i.e., hand detection is performed on the current image by
# HandDetectionSubgraph (because HandLandmarkSubgraph could not identify hand
# presence in the previous image). Otherwise, the latter is selected, which is
# never empty because HandLandmarkSubgraphs processes all images (that went
# through FlowLimiterCaculator).
node {
  calculator: "MergeCalculator"
  input_stream: "hand_rect_from_palm_detections"
  input_stream: "prev_hand_rect_from_landmarks"
  output_stream: "hand_rect"
}

# Add New Node
node {
  calculator: "MyPassThroughCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "NORM_RECT:hand_rect"
  input_stream: "DETECTIONS:palm_detections"
  output_stream: "LANDMARKS:hand_landmarks_out"
  output_stream: "NORM_RECT:hand_rect_out"
  output_stream: "DETECTIONS:palm_detections_out"
}

# Modify input_stream names of next node

# Subgraph that renders annotations and overlays them on top of the input
# images (see renderer_cpu.pbtxt).
node {
  calculator: "RendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "LANDMARKS:hand_landmarks_out"
  input_stream: "NORM_RECT:hand_rect_out"
  input_stream: "DETECTIONS:palm_detections_out"
  output_stream: "IMAGE:output_video"
}

I0428 09:20:50.275421 288341440 demo_run_graph_main.cc:53] Initialize the calculator graph.
E0428 09:20:50.277837 288341440 demo_run_graph_main.cc:146] Failed to run the graph: ValidatedGraphConfig Initialization failed.
No registered object with name: MyPassThroughCalculator; Unable to find Calculator "MyPassThroughCalculator"
```

Did I overlook something? Thanks :)

**Comment by madelinegannon** [comment] 2020-04-28 10:53
Hmmm .... it looks like the compiler can't find `wrapper_hand_tracking.pb.h`. Did you copy the `wrapper_hand_tracker.proto` in this repo's `/mediapipe` [directory](https://github.com/madelinegannon/example-mediapipe-udp/tree/master/mediapipe) into `mediapipe/framework/formats` directory, and add it and its dependencies to `mediapipe/framework/formats/BUILD`:

```
mediapipe_proto_library(
    name = "wrapper_hand_tracking_proto",
    srcs = ["wrapper_hand_tracking.proto"],
    visibility = ["//visibility:public"],
    deps = [
      "//mediapipe/framework/formats:landmark_proto",
      "//mediapipe/framework/formats:detection_proto",
      "//mediapipe/framework/formats:rect_proto",
    ],
)
```

(This step is not called out very well in my instructions. I'll modify the README for clarity, but let me know if that does the trick.)

**Comment by faaip** [comment] 2020-04-28 18:08
Hi Madeline. Sorry this might be me it's been a long time since I tinkered with makefiles and the likes. I tried with a fresh clone of mediapipe, followed the steps and now run into this.

```
INFO: Build option --compilation_mode has changed, discarding analysis cache.
INFO: Analyzed target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu (60 packages loaded, 5056 targets configured).
INFO: Found 1 target...
ERROR: /Users/frederikjuutilainen/Programming/mediapipe/mediapipe/calculators/core/BUILD:1066:1: C++ compilation of rule '//mediapipe/calculators/core:my_pass_through_calculator' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 68 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/core/my_pass_through_calculator.cc:22:10: fatal error: 'mediapipe/framework/formats/wrapper_hand_tracking.pb.h' file not found
#include "mediapipe/framework/formats/wrapper_hand_tracking.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 13.676s, Critical Path: 6.40s
INFO: 5 processes: 5 darwin-sandbox.
FAILED: Build did NOT complete successfully
zsh: no such file or directory: bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu
```

The mediapipe "hello world" works, but maybe it's an issue with mediapipe rather than this repository. Do you know what it could be? :)

**Comment by eightlines** [comment] 2020-04-30 02:53
I'm seeing this same error. I have the wrapper_hand_tracker.proto in the framework/formats directory but I don't see the wrapper_hand_tracking.pb.h. I don't see it in the MediaPipe repo either.

**Comment by eightlines** [comment] 2020-04-30 02:56
Should there be a step to copy the files from this directory https://github.com/madelinegannon/example-mediapipe-udp/tree/master/src/mediapipe/framework/formats to /mediapipe/framework/formats/ ?

**Comment by eightlines** [comment] 2020-04-30 03:01
`mediapipe/calculators/core/my_pass_through_calculator.cc:22:10: fatal error: 'mediapipe/framework/formats/wrapper_hand_tracking.pb.h' file not found
#include "mediapipe/framework/formats/wrapper_hand_tracking.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build`

The file appears to be in the correct location.

**Comment by madelinegannon** [comment] 2020-04-30 13:44
I'm not sure where the error in my instructions are (I appreciate you all working through them and giving feedback). I'll record a video going through the setup and post a link here in the next day or so.

**Comment by cfoster0** [comment] 2020-04-30 19:28
I was able to fix the `'...wrapper_hand_tracking.pb.h' file not found` error by:

1. Making sure that the .proto file is named `wrapper_hand_tracking.proto`, not `wrapper_hand_tracker.proto`.

2. Adding the wrapper proto to the list of dependencies for the pass-through calculator. You can do this by modifying `mediapipe/calculators/core/BUILD` so that `"//mediapipe/framework/formats:wrapper_hand_tracking_cc_proto"` is added to the `deps` list of  the `my_pass_through_calculator` calculator we added in step 3.
i.e. The addition in step 3 should be:

```
cc_library(
    name = "my_pass_through_calculator",
    srcs = ["my_pass_through_calculator.cc"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:status",
        "//mediapipe/framework/formats:landmark_cc_proto",
        "//mediapipe/framework/formats:rect_cc_proto",
        "//mediapipe/framework/formats:detection_cc_proto",
        "//mediapipe/framework/formats:wrapper_hand_tracking_cc_proto",
    ],
    alwayslink = 1,
)
```

**Comment by eightlines** [comment] 2020-04-30 22:04
I can confirm this works for me. The dep line was all I needed.

**Comment by faaip** [comment] 2020-05-01 08:46
Thanks @cfoster0 , works for me! @madelinegannon I added the line in the readme as a PR. Thanks for your work on this again 👍

**Comment by madelinegannon** [comment] 2020-05-01 16:31
Merged Updated BUILD Instructions from @faaip 
Thanks everyone.

**Closed as completed by madelinegannon** 2020-05-01 16:31 UTC

**Comment by DandyLorenz** [comment] 2021-01-06 11:15
> 您还需要修改_mediapipe / graphs / hand_tracking / BUILD_文件以将新计算器添加为依赖项：
> 
> ```
> cc_library(
>     name = "desktop_offline_calculators",
>     deps = [
>         "//mediapipe/calculators/core:flow_limiter_calculator",
>         "//mediapipe/calculators/core:gate_calculator",
>         "//mediapipe/calculators/core:immediate_mux_calculator",
>         "//mediapipe/calculators/core:packet_inner_join_calculator",
>         "//mediapipe/calculators/core:previous_loopback_calculator",
>         "//mediapipe/calculators/video:opencv_video_decoder_calculator",
>         "//mediapipe/calculators/video:opencv_video_encoder_calculator",
>         "//mediapipe/calculators/core:my_pass_through_calculator"
>     ],
> )
> ```
> 
> 感谢您指出了这一点！自述文件中缺少此步骤。我现在将其添加:)
> 
> 让我知道它的工作原理以及是否遇到其他问题。

You are very experienced.Have you solved the problem? When I building AAR, an error was reported: No registered calculator found: xxx,
How to add the calculators node in the BUILD file? See the link for details：https://github.com/google/mediapipe/issues/1450
